version: '3.8'

services:
  microservicio5:
    image: microservicio5:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8099:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mysql5

  mysql5:
    image: mysql:8.0
    ports:
      - "3315:3306"
    environment:
      MYSQL_ROOT_PASSWORD: P4ssword!
      MYSQL_DATABASE: my-app